// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7KcY5bHEesX2TZbzyi9hhprB0xJEPeQ',
    appId: '1:651538870844:web:35f94e9a7330c66a87c939',
    messagingSenderId: '651538870844',
    projectId: 'realtime-schedule-b941f',
    authDomain: 'realtime-schedule-b941f.firebaseapp.com',
    databaseURL: 'https://realtime-schedule-b941f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-schedule-b941f.firebasestorage.app',
    measurementId: 'G-KDQKCPLLVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHwzQF5Fgmr601AvanxB1It-HccUHW7o4',
    appId: '1:651538870844:android:b5020b617f13af2087c939',
    messagingSenderId: '651538870844',
    projectId: 'realtime-schedule-b941f',
    databaseURL: 'https://realtime-schedule-b941f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-schedule-b941f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANMuPOdVf4f6MA4AQyX_mHBF8_37P_USs',
    appId: '1:651538870844:ios:64036e44c6ff295287c939',
    messagingSenderId: '651538870844',
    projectId: 'realtime-schedule-b941f',
    databaseURL: 'https://realtime-schedule-b941f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-schedule-b941f.firebasestorage.app',
    iosClientId: '651538870844-qaq2q3pueiqv3c3umqh8sed3vmcsajqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.jadwalRealtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANMuPOdVf4f6MA4AQyX_mHBF8_37P_USs',
    appId: '1:651538870844:ios:64036e44c6ff295287c939',
    messagingSenderId: '651538870844',
    projectId: 'realtime-schedule-b941f',
    databaseURL: 'https://realtime-schedule-b941f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-schedule-b941f.firebasestorage.app',
    iosClientId: '651538870844-qaq2q3pueiqv3c3umqh8sed3vmcsajqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.jadwalRealtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ7KcY5bHEesX2TZbzyi9hhprB0xJEPeQ',
    appId: '1:651538870844:web:65f500cd2de9e98587c939',
    messagingSenderId: '651538870844',
    projectId: 'realtime-schedule-b941f',
    authDomain: 'realtime-schedule-b941f.firebaseapp.com',
    databaseURL: 'https://realtime-schedule-b941f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-schedule-b941f.firebasestorage.app',
    measurementId: 'G-50EBPR9JXX',
  );

}